# Generated by Django 4.2 on 2023-04-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=4)),
                ('seed', models.CharField(max_length=255)),
                ('private_key', models.CharField(max_length=255)),
                ('public_key', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('wif', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
